# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'MockServer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MockServer

  target 'MockServerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MockServerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

    pod 'ObjectMapper'
    pod 'RxSwift'
    pod 'RxCocoa'

end
